server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    enable-self-preservation: false

  # ================================
  # Local setup (when running outside Docker)
  # ================================
  # instance:
  #   hostname: 127.0.0.1
  #   serviceUrl:
  #     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  # ================================
  # Docker setup (when running inside docker-compose)
  # ================================
  instance:
    hostname: discovery-ser
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
