spring:
  application:
    name: config-server
  profiles:
    active: native

server:
  port: 8888

# ================================
# Local setup
# ================================
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/

# ================================
# Docker setup
# ================================
eureka:
  client:
    service-url:
      defaultZone: http://discovery-ser:8761/eureka/
