spring:
  application:
    name: CART-SERVICE

server:
  port: 8080   # for running local this will be 8081

# ================================
# Local setup
# ================================
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/

# ================================
# Docker setup
# ================================
eureka:
  client:
    service-url:
      defaultZone: http://discovery-ser:8761/eureka/
  instance:
    hostname: ${HOSTNAME}       # Docker container name
    prefer-ip-address: true
    non-secure-port: 8080
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# ================================
# External service URLs for CartService -
# ================================
checkout-service:
  url: http://checkout-service:8080/api/v1/checkout

# ================================
# i18n Messages
# ================================
messages:
  basename: messages
  encoding: UTF-8

# ================================
# HTTP Timeouts
# ================================
#http:
#  connect-timeout-ms: 2000   # 2 seconds
#  read-timeout-ms: 5000      # 5 seconds
