FROM ecommerce-app:latest AS builder
WORKDIR /app

COPY pom.xml .
COPY base-framework ./base-framework
COPY microservices ./microservices
COPY infra-services ./infra-services

RUN mvn -pl infra-services/config-ser -am clean package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app

COPY --from=builder /app/infra-services/config-ser/target/config-ser-*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
