server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    config:
      enabled: false

    gateway:
      routes:
        - id: cart-service
          #uri: lb://CART-SERVICE  Need to setup
          ##Add an entry so DESKTOP-1MC66TN.mshome.net resolves to your local machine IP (e.g., 127.0.0.1).
          #
          #Example (Windows C:\Windows\System32\drivers\etc\hosts):
          # Map host in /etc/hosts
          uri: http://localhost:8081      # Direct backend URL, bypass Eureka
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=0
        - id: checkout-service
          uri: http://localhost:8082
          predicates:
            - Path=/checkout/**
          filters:
            - StripPrefix=0
        - id: discount-service
          uri: http://localhost:8083
          predicates:
            - Path=/discount/**
          filters:
            - StripPrefix=0
        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=0
        - id: admin-service
          uri: http://localhost:8085
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=0

# Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG


