server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    config:
      enabled: false

    gateway:
      routes:
        # ================================
        # Local setup
        # ================================
        # - id: cart-service
        #   uri: http://localhost:8081
        #   predicates:
        #     - Path=/cart/**
        #   filters:
        #     - StripPrefix=0
        # - id: checkout-service
        #   uri: http://localhost:8082
        #   predicates:
        #     - Path=/checkout/**
        #   filters:
        #     - StripPrefix=0
        # - id: discount-service
        #   uri: http://localhost:8083
        #   predicates:
        #     - Path=/discount/**
        #   filters:
        #     - StripPrefix=0
        # - id: order-service
        #   uri: http://localhost:8084
        #   predicates:
        #     - Path=/order/**
        #   filters:
        #     - StripPrefix=0
        # - id: admin-service
        #   uri: http://localhost:8085
        #   predicates:
        #     - Path=/admin/**
        #   filters:
        #     - StripPrefix=0

        # ================================
        # Docker setup  via Eureka)
        # ================================
        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/api/v1/cart/**
          filters:
            - StripPrefix=0

        # Actuator route for cart-service
        - id: cart-actuator
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart/actuator/**
          filters:
            - StripPrefix=1

        - id: checkout-service
          uri: lb://CHECKOUT-SERVICE
          predicates:
            - Path=/checkout/**
          filters:
            - StripPrefix=0
        - id: discount-service
          uri: lb://DISCOUNT-SERVICE
          predicates:
            - Path=/discount/**
          filters:
            - StripPrefix=0
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=0
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/api/v1/admin/**
          filters:
            - StripPrefix=0

# ================================
# Local setup
# ================================
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/

# ================================
# Docker setup
# ================================
eureka:
  client:
    service-url:
      defaultZone: http://discovery-ser:8761/eureka/

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
